# Generated by Django 2.2.2 on 2021-07-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_host_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='project',
        ),
    ]
