# Generated by Django 2.2.2 on 2021-07-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_remove_host_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
